tasks:
  - init: ./gradlew clean build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension
    - jebbs.plantuml@2.13.12:q7DiD6H5NTesaWYIXmeMMQ==
