name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Gradle caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Install Graphviz
      run: sudo apt-get install -y graphviz
    - name: Generate image artifacts
      run: java -jar ./build/libs/context-mapper-standalone-example-1.0.0-SNAPSHOT.jar -f ./src/main/cml/Insurance-Example-Model.cml -t contextmap
    - name: Generate PlantUML artifacts
      run: java -jar ./build/libs/context-mapper-standalone-example-1.0.0-SNAPSHOT.jar -f ./src/main/cml/Insurance-Example-Model.cml -t plantuml
    - name: Generate MDSL artifacts
      run: java -jar ./build/libs/context-mapper-standalone-example-1.0.0-SNAPSHOT.jar -f ./src/main/cml/Insurance-Example-Model.cml -t mdsl
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: diagrams
        path: src-gen/
